from typing import Optional, List
from mongoengine import ObjectIdField
from pydantic import BaseModel, Field


class AccountPost(BaseModel):
    _id: ObjectIdField()
    name: str = Field(
        default="",
        alias="name",
        title="Name of user",
        description="Name of user",
        max_length=100,
        examples=["User 1"])
    email: str = Field(
        default="",
        alias="email",
        title="Email of user",
        description="Email of user",
        max_length=100,
        examples=["teste@mios.pt"])
    password: str = Field(
        default="",
        alias="password",
        title="Password of user",
        description="Password of user",
        max_length=100)
    gmail_access_token: Optional[str] = Field(
        default="",
        alias="gmail_access_token",
        title="Gmail access token of user",
        description="Gmail access token of user",
        max_length=100,
        examples=["123456"])
    apple_access_token: Optional[str] = Field(
        default="",
        alias="apple_access_token",
        title="Apple access token of user",
        description="Apple access token of user",
        max_length=100,
        examples=["123456"])
    facebook_access_token: Optional[str] = Field(
        default="",
        alias="facebook_access_token",
        title="Facebook access token of user",
        description="Facebook access token of user",
        max_length=100,
        examples=["123456"])
    discord_access_token: Optional[str] = Field(
        default="",
        alias="discord_access_token",
        title="Discord access token of user",
        description="Discord access token of user",
        max_length=100,
        examples=["123456"])
    twitter_access_token: Optional[str] = Field(
        default="",
        alias="twitter_access_token",
        title="Twitter access token of user",
        description="Twitter access token of user",
        max_length=100,
        examples=["123456"])
    photo_profile: Optional[str] = Field(
        default="",
        alias="photo_profile",
        title="Photo profile of user",
        description="Photo profile of user",
        max_length=100,
        examples=["https://www.image.com.br"])
    birthday: Optional[str] = Field(
        default="",
        alias="birthday",
        title="Birthday of user",
        description="Birthday of user",
        max_length=100,
        examples=["2021-01-01 00:00:00"])
    bio: Optional[str] = Field(
        default="",
        alias="bio",
        title="Bio of user",
        description="Bio of user",
        max_length=5000,
        examples=["Bio of user"])
    code_access: Optional[str] = Field(
        default="",
        alias="code_access",
        title="Code access of user",
        description="Code access of user",
        max_length=6,
        examples=["123456"])
